### ISSUE TITLE
New Fw ver (A1 mini)

### ISSUE THREAD

**Issue by MaxHarm** [lunDreame/user-bambulab-firmware#10]
New Version 01.03.01.02 A1 mini 
Please update if you can/

**Comment by anhnvme** [comment]
also A1. please update. thank you

**Comment by yeorinhieut** [comment]
Will update a1 mini firmware in few days.
A1 firmware update is still unclear cause I don't have it... Its better to find somebody who use a1 global version.

**Comment by yeorinhieut** [comment]
added
