### ISSUE TITLE
new firmware P1S 01.06.01.02

### ISSUE THREAD

**Issue by kostake2011** [lunDreame/user-bambulab-firmware#11]
Please update the code so that it can be updated to 01.06.01.02 P1S +AMS

**Comment by necroave** [comment]
{
    "user_id": "0",
    "upgrade": {
        "sequence_id": "0",
        "command": "upgrade_history",
        "src_id": 2,
        "firmware_optional": {
            "firmware": {
                "version": "01.06.01.02",
                "url": "https://public-cdn.bblmw.cn/upgrade/device/C12/01.06.01.02/product/e70b5f9580/ota-p003_v01.06.01.02-20240926182734.json.sig",
                "force_update": false,
                "description": "# Verison 01.06.01.02\n\n## Improvement\n\n1. Improved printing stability.\n2. Optimized read-and-write compatibility for MicroSD cards.\n",
                "status": "release"
            },
            "ams": [
                {
                    "dev_model_name": "BL-A001",
                    "address": 0,
                    "device_id": "",
                    "firmware": [
                        {
                            "version": "00.00.06.40",
                            "force_update": false,
                            "url": "https://public-cdn.bambulab.com/upgrade/device/BL-A001/00.00.06.40/product/ams-ota_v00.00.06.40-20230906131441.json.sig",
                            "description": "",
                            "status": "testing"
                        }
                    ],
                    "firmware_current": null
                }
            ]
        }
    }
}

**Comment by kostake2011** [comment]
Thank you

**Comment by yeorinhieut** [comment]
added!
