### ISSUE TITLE
NEW FIRMWARE FOR A1

### ISSUE THREAD

**Issue by Salmonings** [lunDreame/user-bambulab-firmware#12]
I have the Chinese version of A1. I am Chinese but live outside. I've connected the printer to account before but when I left I can't do it anymore. Version no: 01.03.01.02

**Comment by yeorinhieut** [comment]
Finding contributors with global a1...
Will be added in couple weeks

**Comment by ducvd89** [comment]
Please update 01.04 for A1. It's an important version. Thank you!

**Comment by yeorinhieut** [comment]
https://bambulab.com/en/support/firmware-download/all

You can try offline firmware update via this link.
Bambulab is now supporting firmware update via sd card.

**Comment by ducvd89** [comment]
Sadly, Mine still on 01.03 which can't upgrade via sdcard. sdcard upgrade only avail. from 01.04 :(

**Comment by JayFoxRox** [comment]
I've crafted the following URLs from the offline URL (untested):

- Steps:
    - Remove /offline/
    - Add /product/
    - Remove offline-
    - Change extension to json.sig

- Examples:
    - A1 Mini 
        - SD: https://public-cdn.bblmw.com/upgrade/device/offline/N1/01.04.00.00/1496eccbb7/offline-ota-n1_v01.04.00.00-20241210144819.zip
        - OTA: https://public-cdn.bblmw.com/upgrade/device/N1/01.04.00.00/product/1496eccbb7/ota-n1_v01.04.00.00-20241210144819.json.sig
    - A1
        - SD: https://public-cdn.bblmw.com/upgrade/device/offline/N2S/01.04.00.00/1496eccbb7/offline-ota-n2s_v01.04.00.00-20241210144933.zip
        - OTA: https://public-cdn.bblmw.com/upgrade/device/N2S/01.04.00.00/product/1496eccbb7/ota-n2s_v01.04.00.00-20241210144933.json.sig

Again, I've not tested these, but the generated OTA URLs *do* exist.

**Comment by lunDreame** [comment]
@JayFoxRox 
Good!, can you please tell me the firmware address of the AMS Lite for the A1, A1 Mini? I tried backtracking and came up with a plausible address, but it doesn't connect to the site.

https://public-cdn.bambulab.com/upgrade/device/AMS_F1/00.00.07.94/product/ams-f1-ota_v00.00.07.94-20240703100634.json.sig        Not working

https://public-cdn.bblmw.com/upgrade/device/AMS_F1/00.00.07.94/product/1496eccbb7/ams-f1-ota_v00.00.07.94-20240703100634.json.sig        Not working

**Comment by ducvd89** [comment]
Command for A1 01.04 update. Tested.

{
    "user_id": "0",
    "upgrade": {
        "sequence_id": "0",
        "command": "upgrade_history",
        "src_id": 2,
        "firmware_optional": {
            "firmware": {
                "version": "01.04.00.00",
                "url": "https://public-cdn.bblmw.com/upgrade/device/N2S/01.04.00.00/product/1496eccbb7/ota-n2s_v01.04.00.00-20241210144933.json.sig",
                "force_update": false,
                "description": "",
                "status": "release"
            },
            "ams": []
        }
    }
}

**Comment by JayFoxRox** [comment]
> @JayFoxRox Good!, can you please tell me the firmware address of the AMS Lite for the A1, A1 Mini? I tried backtracking and came up with a plausible address, but it doesn't connect to the site.
> 
> https://public-cdn.bambulab.com/upgrade/device/AMS_F1/00.00.07.94/product/ams-f1-ota_v00.00.07.94-20240703100634.json.sig Not working
> 
> https://public-cdn.bblmw.com/upgrade/device/AMS_F1/00.00.07.94/product/1496eccbb7/ams-f1-ota_v00.00.07.94-20240703100634.json.sig Not working

I did now also notice the offline update includes the AMS, but the OTA doesn't. I've also experimented with possible AMS URLs now and couldn't find anything either.

However, I don't think it matters that much, because you can use the OTA update to get to the latest version, and then continue with SD updates to also bring the AMS to the right version?

**Comment by eightheads** [comment]
> Command for A1 01.04 update. Tested.
> 
> { "user_id": "0", "upgrade": { "sequence_id": "0", "command": "upgrade_history", "src_id": 2, "firmware_optional": { "firmware": { "version": "01.04.00.00", "url": "https://public-cdn.bblmw.com/upgrade/device/N2S/01.04.00.00/product/1496eccbb7/ota-n2s_v01.04.00.00-20241210144933.json.sig", "force_update": false, "description": "", "status": "release" }, "ams": [] } } }

I have a CN A1 currently on OTA: 01.03.30.01 and trying to update the firmware to at least 01.04 so I can do SD card updates, but cannot seem to get it to update using the above. I'm getting the following failure message:

{"print":{"wifi_signal":"-45dBm","upgrade_state":{"status":"UPGRADE_FAIL","dis_state":3},"ipcam":{"ipcam_dev":"1"},"command":"push_status","msg":1,"sequence_id":"236"}}

**Comment by Aahil78** [comment]
Can anyone do this for the newer v1.08.00.00 firmware? Thanks!
