### ISSUE TITLE
Does not want to update

### ISSUE THREAD

**Issue by Salmonings** [lunDreame/user-bambulab-firmware#15]
Bambu Lab A1 when trying to update to v01.04.00.00 mqttx gives this:
{"upgrade":{"sequence_id":"0","command":"upgrade_history","src_id":2,"firmware_optional":{"firmware":{"version":"01.04.00.00","url":"https://public-cdn.bblmw.com/upgrade/device/N2S/01.04.00.00/product/1496eccbb7/ota-n2s_v01.04.00.00-20241210144933.json.sig","force_update":false,"description":"","status":"release"},"ams":[{}]},"result":"fail"}}
And the screen says update failed
I have tried both scripts: A1 and A1 Mini. None work. The older versions does work tho

**Comment by lunDreame** [comment]
{
    "user_id": "0",
    "upgrade": {
        "sequence_id": "0",
        "command": "upgrade_history",
        "src_id": 2,
        "firmware_optional": {
            "firmware": {
                "version": "01.04.00.00",
                "url": "https://public-cdn.bblmw.com/upgrade/device/N2S/01.04.00.00/product/1496eccbb7/ota-n2s_v01.04.00.00-20241210144933.json.sig",
                "force_update": false,
                "description": "",
                "status": "release"
            },
            "ams": []
        }
    }
}

Would you like to try this?

**Comment by Salmonings** [comment]
OH MY GOD THANK YOU SO MUCH PLEASE CHANGE THIS IN THE FILE IT WORKS YAY
