### ISSUE TITLE
A1 mini version 01.03.00.00 (20240612)

### ISSUE THREAD

**Issue by DangViTin** [lunDreame/user-bambulab-firmware#6]
I try to update my A1 mini but file "A1_MINI_AMS. json" seem to have the old version, can you please update it to the newest version. That would be really helpful.

**Comment by MaxHarm** [comment]
Yes! Please UPDATE!

**Comment by lunDreame** [comment]
@yeorinhieut

**Comment by MaxHarm** [comment]
> @yeorinhieut
He uses a file from your repository. And your latest version is 01.02.02.40. Is there a link to 01.03.00.00?

**Comment by yeorinhieut** [comment]
Updated a1 mini firmware version to 01.03.00.00
@MaxHarm @dangvitin

**Comment by MaxHarm** [comment]
> Updated a1 mini firmware version to 01.03.00.00 @MaxHarm @dangvitin

Thank you very much!

**Comment by JayFoxRox** [comment]
They just released "Version 01.03.01.00 (20240722)" according to https://wiki.bambulab.com/en/a1-mini/manual/a1-mini-firmware-release-history

CC @yeorinhieut

**Comment by yeorinhieut** [comment]
I sold my printer about 3 days ago and purchased a1... It will take some time to update

**Comment by yeorinhieut** [comment]
Updated!

@JayFoxRox
