### ISSUE TITLE
Can not run on Mac M2

### ISSUE THREAD

**Issue by BigVeila** [lunDreame/user-bambulab-firmware#7]
![Screenshot 2024-07-17 at 16 22 37](https://github.com/user-attachments/assets/a6e5689e-fdb9-4b8c-ad90-a262169ca9ac)
I can not run on Mac M2, Ventura 13.5

**Comment by lunDreame** [comment]
I don't know what the problem is because the decoding is broken. what's the problem?

**Comment by lunDreame** [comment]
@BigVeila [Instructions](https://bambu.pages.dev/update) was added to the site.
