### ISSUE TITLE
New firmware for A1  01.03.01.00 (20240722)

### ISSUE THREAD

**Issue by anhnvme** [lunDreame/user-bambulab-firmware#8]
Hello,

That good to see this repo, thank for all.
I see A1 have a new firmware. Could you update new firmware for this model.
I just sell A1 mini to get A1 then see A1 mini have new firmware 🤣 

Thank you

**Comment by lunDreame** [comment]
I'will take soon update

**Comment by JayFoxRox** [comment]
It had already been updated yesterday in https://github.com/lunDreame/user-bambulab-firmware/commit/10c87b34ba329b6d5a8c268819238ecd88b1929d after discussion in https://github.com/lunDreame/user-bambulab-firmware/issues/6#issuecomment-2242856980

**Comment by yeorinhieut** [comment]
Looking forward to update this, maybe in few days

**Comment by yeorinhieut** [comment]
Updated! @anhnvme
